# -*- coding: utf-8 -*-
"""Copy of Copy of seawise-giant.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wtho4d0-q_T5IIsH3KWgqcXZQSoM1d0W
"""

import numpy as np
import pandas as pd


import os
for dirname, _, filenames in os.walk('/content/sample_data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))



pip install mljar-supervised

from supervised.automl import AutoML

train = pd.read_csv("/content/sample_data/train.csv")
test = pd.read_csv("/content/sample_data/test.csv")

train

def seawiseGiant_features(dataframe) :
    df = dataframe
    df["Embarked"] = df["Embarked"].fillna("S")
    df["Sex"] = df["Sex"].map({"female":0, "male":1})
    df["Family"] = df["SibSp"]+df["Parch"]+1
    df['IsAlone'] = 0
    df.loc[df['Family'] == 1, 'IsAlone'] = 1
    df["Deck"] = df["Cabin"].apply(lambda x : "0" if pd.isna(x) else x[0])
    df = df.drop(["PassengerId", "Name", "Ticket", "Cabin", "SibSp", "Parch"], axis=1)
    return df

train = seawiseGiant_features(train)
test = seawiseGiant_features(test)

train

#X will contain all the features and y will contain the target variable
y_train = train["Survived"]
X_train = train.drop(["Survived"], axis=1)

from supervised.preprocessing.eda import EDA

EDA.extensive_eda(X_train,y_train,save_path=".")

automl = AutoML(mode="Explain", eval_metric="accuracy")

automl.fit(X_train, y_train)

automl.report()